name: CI

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Install Clang and libc++
        run: |
          sudo apt-get update
          sudo apt-get install -y clang libc++-14-dev libc++abi-14-dev

      - name: Configure with CMake
        run: |
          mkdir build
          cd build
          cmake -DCMAKE_C_COMPILER=clang -DCMAKE_CXX_COMPILER=clang++ -DCMAKE_CXX_FLAGS="-stdlib=libc++ -L/usr/lib/x86_64-linux-gnu" -DCMAKE_EXE_LINKER_FLAGS="-stdlib=libc++" -DCMAKE_BUILD_TYPE=Release ..

      - name: Build
        run: |
          cmake --build build --config Release --parallel

      - name: Run Test
        run: /home/runner/work/github_actions_gtest_example/github_actions_gtest_example/build/test/github_actions_gtest_example.test
